'use client';
import {useEffect,useState} from 'react';
import {uploadFileToR2} from '@/lib/browser-r2';
function fmt(n:number){if(!Number.isFinite(n))return '';if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
export default function UploadWorkspace({workspaceId}:{workspaceId:string}){
 const[data,setData]=useState<any>(null),[message,setMessage]=useState(''),[messages,setMessages]=useState<any[]>([]),[chat,setChat]=useState('');
 const[progress,setProgress]=useState<Record<string,number>>({}),[selected,setSelected]=useState<Record<string,boolean>>({}),[deleting,setDeleting]=useState(false);
 const load=async()=>{const r=await fetch(`/api/r2/deliverables?workspace_id=${workspaceId}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)};
 useEffect(()=>{load().catch(e=>setMessage(e.message));fetch(`/api/commission-messages?workspace_id=${workspaceId}`).then(r=>r.json()).then(j=>setMessages(j.messages||[])).catch(()=>{})},[workspaceId]);
 const send=async()=>{if(!chat.trim())return;const r=await fetch('/api/commission-messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,body:chat})});const j=await r.json();if(!r.ok){setMessage(j.error||'Message failed');return}setMessages(x=>[...x,j.message]);setChat('')};
 const upload=async(deliverableId:string,file:File)=>{const key=`${deliverableId}:${file.name}:${file.lastModified}`;setProgress(x=>({...x,[key]:0}));setMessage(`Uploading ${file.name}…`);try{await uploadFileToR2('/api/r2/deliverables',{workspace_id:workspaceId,deliverable_id:deliverableId},file,p=>setProgress(x=>({...x,[key]:p})));await load();setMessage(`${file.name} uploaded successfully.`)}catch(e){setMessage(e instanceof Error?e.message:'Upload failed.')}finally{setTimeout(()=>setProgress(x=>{const y={...x};delete y[key];return y}),1500)}};
 const submitDeliverable=async(deliverableId:string)=>{if(!confirm('Submit this deliverable to Plekxa for review? You can still respond to a revision request later.'))return;setMessage('Submitting deliverable for review…');try{const r=await fetch('/api/r2/deliverables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,deliverable_id:deliverableId,action:'submit'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Submission failed');await load();setMessage('Deliverable submitted. Plekxa has been notified.')}catch(e){setMessage(e instanceof Error?e.message:'Submission failed')}};
 const remove=async()=>{const ids=Object.keys(selected).filter(id=>selected[id]);if(!ids.length)return;if(!confirm(`Delete ${ids.length} selected file${ids.length===1?'':'s'}? This also removes the file${ids.length===1?'':'s'} from Cloudflare R2.`))return;setDeleting(true);setMessage('Deleting selected files…');try{const r=await fetch('/api/r2/deliverables',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,ids})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Delete failed');setSelected({});await load();setMessage(`${j.deleted} file${j.deleted===1?'':'s'} deleted.`)}catch(e){setMessage(e instanceof Error?e.message:'Delete failed.')}finally{setDeleting(false)}};
 if(!data)return <section className="projects-empty-state"><p>{message||'Loading workspace…'}</p></section>;
 const deletableDeliverables=(data.deliverables||[]).filter((d:any)=>!['accepted','approved'].includes(String(d.review_status||d.status||'').toLowerCase()));
 const allFiles=deletableDeliverables.flatMap((d:any)=>d.files||[]), selectedCount=Object.values(selected).filter(Boolean).length;
 return <div><header className="creator-page-heading"><span className="eyebrow">WORKSPACE</span><h1>{data.workspace.title}</h1><p>Milestones, deliverables, files and conversation for this commission.</p></header>
 {message&&<p role="status">{message}</p>}{data.reference_files?.length?<section className="projects-empty-state" style={{marginBottom:16,textAlign:'left'}}><h2>Project files from Plekxa</h2><p>Download the beats, samples, briefs, stems or reference files supplied for this commission.</p>{data.reference_files.map((f:any)=><div key={f.id} style={{padding:'8px 0'}}><a className="button" href={f.download_url} target="_blank" rel="noreferrer">Download {f.file_name}</a> <span>{fmt(Number(f.size_bytes||0))}</span></div>)}</section>:null}
 {allFiles.length>0&&<div style={{display:'flex',gap:12,alignItems:'center',marginBottom:16,flexWrap:'wrap'}}><label><input type="checkbox" checked={allFiles.length>0&&allFiles.every((f:any)=>selected[f.id])} onChange={e=>setSelected(Object.fromEntries(allFiles.map((f:any)=>[f.id,e.target.checked])))} /> Select all files</label><button className="button" disabled={!selectedCount||deleting} onClick={()=>void remove()}>Delete selected{selectedCount?` (${selectedCount})`:''}</button></div>}
 {data.deliverables?.length?data.deliverables.map((d:any)=><section className="projects-empty-state" key={d.id} style={{marginBottom:16,textAlign:'left'}}><h2>{d.title}</h2><p>{d.status}{d.due_at?` · Due ${new Date(d.due_at).toLocaleDateString('en-GB')}`:''}</p>{d.approval_notes?<p><strong>Instructions:</strong> {d.approval_notes}</p>:null}{['accepted','approved'].includes(String(d.review_status||d.status||'').toLowerCase())?<p><strong>Accepted by Plekxa.</strong> This deliverable is locked. Contact the Plekxa team if a correction is required.</p>:<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><label className="button">Choose files<input hidden type="file" multiple onChange={e=>{for(const f of Array.from(e.target.files||[]))void upload(d.id,f);e.currentTarget.value=''}}/></label><label className="button">Choose folder<input hidden type="file" multiple {...({webkitdirectory:'',directory:''} as any)} onChange={e=>{for(const f of Array.from(e.target.files||[]))void upload(d.id,f);e.currentTarget.value=''}}/></label></div>}
 {Object.entries(progress).filter(([k])=>k.startsWith(`${d.id}:`)).map(([k,p])=><div key={k} style={{marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><span>{k.split(':')[1]}</span><strong>{p}%</strong></div><progress value={p} max={100} style={{width:'100%'}} /></div>)}
 {d.files?.length?<div style={{marginTop:14}}>{d.files.map((f:any)=><div key={f.id} style={{display:'flex',gap:10,alignItems:'center',padding:'8px 0',flexWrap:'wrap'}}>{!['accepted','approved'].includes(String(d.review_status||d.status||'').toLowerCase())?<input type="checkbox" aria-label={`Select ${f.file_name}`} checked={!!selected[f.id]} onChange={e=>setSelected(x=>({...x,[f.id]:e.target.checked}))}/>:null}<a href={f.download_url||'#'} target="_blank" rel="noreferrer">{f.file_name}</a><span>{fmt(Number(f.size_bytes||0))} · version {f.version}</span></div>)}{!['accepted','approved'].includes(String(d.review_status||d.status||'').toLowerCase())&&String(d.status||'').toLowerCase()!=='submitted'?<button className="button" style={{marginTop:12}} onClick={()=>void submitDeliverable(d.id)}>Submit deliverable for review</button>:String(d.status||'').toLowerCase()==='submitted'?<p><strong>Submitted to Plekxa for review.</strong></p>:null}</div>:<p style={{marginTop:14}}>No files uploaded yet. Upload your work, check the files, then click <strong>Submit deliverable for review</strong>.</p>}</section>):<section className="projects-empty-state"><h2>No deliverables assigned yet</h2><p>Your assigned deliverables will appear here.</p></section>}
 <section className="projects-empty-state" style={{textAlign:'left',maxWidth:'none'}}><h2>Conversation</h2><p>Use this thread for questions, feedback and delivery context. New messages notify Plekxa in-app and by email.</p><div style={{border:'1px solid #ddd',borderRadius:14,padding:18,minHeight:260,maxHeight:520,overflowY:'auto',marginBottom:14}}>{messages.length?messages.map((m:any)=><div key={m.id} style={{maxWidth:'82%',marginLeft:m.sender_side==='creator'?'auto':0,marginBottom:12,padding:'10px 13px',borderRadius:12,background:'#f4f4f4'}}><strong>{m.sender_side==='creator'?'You':'Plekxa'}</strong><div>{m.body}</div></div>):<p>No messages yet.</p>}</div><textarea style={{width:'100%'}} rows={5} value={chat} onChange={e=>setChat(e.target.value)} placeholder="Write a message…"/><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button className="button" disabled={!chat.trim()} onClick={()=>void send()}>Send message</button></div></section></div>
}
