function xhrPut(url:string,body:Blob,contentType:string,onProgress?:(loaded:number,total:number)=>void){
 return new Promise<string|null>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);x.setRequestHeader('Content-Type',contentType);x.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(e.loaded,e.total)};x.onerror=()=>reject(new Error('Network error while uploading to R2.'));x.onabort=()=>reject(new Error('Upload cancelled.'));x.onload=()=>x.status>=200&&x.status<300?resolve(x.getResponseHeader('ETag')):reject(new Error(`R2 upload failed (${x.status}).`));x.send(body)});
}
export async function uploadFileToR2(endpoint:string,base:Record<string,any>,file:File,onProgress?:(pct:number)=>void){
 const relative=(file as File & {webkitRelativePath?:string}).webkitRelativePath||file.name; const common={...base,file_name:file.name,relative_path:relative,mime_type:file.type||'application/octet-stream',size_bytes:file.size};
 onProgress?.(0);
 const prep=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...common,action:file.size<=5*1024**3?'presign':'multipart-create'})});const s=await prep.json();if(!prep.ok)throw new Error(s.error||`Could not prepare ${file.name}`);
 if(s.mode==='single'){await xhrPut(s.upload_url,file,common.mime_type,(loaded,total)=>onProgress?.(Math.min(99,Math.round(loaded/total*100))));onProgress?.(100)}else{const partSize=Number(s.part_size||100*1024*1024),count=Math.ceil(file.size/partSize);if(count>10000)throw new Error('File is too large for the configured multipart size.');const parts=[];try{for(let i=0;i<count;i++){const pr=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,action:'multipart-part',key:s.key,upload_id:s.upload_id,part_number:i+1})});const pj=await pr.json();if(!pr.ok)throw new Error(pj.error||'Could not prepare upload part');const blob=file.slice(i*partSize,Math.min(file.size,(i+1)*partSize));const etag=await xhrPut(pj.upload_url,blob,common.mime_type,(loaded,total)=>{const completed=i*partSize;onProgress?.(Math.min(99,Math.round((completed+loaded)/file.size*100))) });if(!etag)throw new Error('R2 did not return an ETag. Expose ETag in the bucket CORS policy.');parts.push({part_number:i+1,etag})}const done=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,action:'multipart-complete',key:s.key,upload_id:s.upload_id,parts})});if(!done.ok)throw new Error((await done.json()).error||'Could not complete multipart upload');onProgress?.(100)}catch(e){await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,action:'multipart-abort',key:s.key,upload_id:s.upload_id})}).catch(()=>{});throw e}}
 const c=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...common,action:'confirm',key:s.key})});const cj=await c.json();if(!c.ok)throw new Error(cj.error||`Could not register ${file.name}`);return cj;
}
