import {NextResponse} from 'next/server';import {createClient} from '@/lib/supabase/server';import {createAdminClient} from '@/lib/supabase/admin';import {PutObjectCommand,CreateMultipartUploadCommand,UploadPartCommand,CompleteMultipartUploadCommand,AbortMultipartUploadCommand} from '@aws-sdk/client-s3';import {getSignedUrl} from '@aws-sdk/s3-request-presigner';import {r2Client,safeFileName} from '@/lib/r2';
const INTERNAL=process.env.CLOUDFLARE_R2_INTERNAL_BUCKET||'plekxa-internal';
async function ctx(projectId:string){const s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated'),{status:401});const a=createAdminClient(),{data:p}=await a.from('projects').select('id,director_user_id').eq('id',projectId).maybeSingle();if(!p||p.director_user_id!==user.id)throw Object.assign(new Error('Director access required'),{status:403});return {user,a}}
export async function POST(r:Request){try{const b=await r.json(),projectId=String(b.project_id||''),{user,a}=await ctx(projectId),action=String(b.action||'presign'),c=r2Client();
 if(action==='presign'||action==='multipart-create'){const name=String(b.relative_path||b.file_name||'');const type=String(b.mime_type||'application/octet-stream'),size=Number(b.size_bytes||0);if(!name||size<=0)return NextResponse.json({error:'File name and size required'},{status:400});const key=`projects/${projectId}/reference/${crypto.randomUUID()}-${safeFileName(name)}`;if(action==='presign'&&size<=5*1024**3)return NextResponse.json({mode:'single',upload_url:await getSignedUrl(c,new PutObjectCommand({Bucket:INTERNAL,Key:key,ContentType:type}),{expiresIn:3600}),key,bucket:INTERNAL});const x=await c.send(new CreateMultipartUploadCommand({Bucket:INTERNAL,Key:key,ContentType:type}));return NextResponse.json({mode:'multipart',upload_id:x.UploadId,key,bucket:INTERNAL,part_size:Math.max(100*1024*1024,Math.ceil(size/9999))})}
 if(action==='multipart-part')return NextResponse.json({upload_url:await getSignedUrl(c,new UploadPartCommand({Bucket:INTERNAL,Key:b.key,UploadId:b.upload_id,PartNumber:Number(b.part_number)}),{expiresIn:3600})});
 if(action==='multipart-complete'){await c.send(new CompleteMultipartUploadCommand({Bucket:INTERNAL,Key:b.key,UploadId:b.upload_id,MultipartUpload:{Parts:(b.parts||[]).map((x:any)=>({ETag:x.etag,PartNumber:Number(x.part_number)}))}}));return NextResponse.json({ok:true})}
 if(action==='multipart-abort'){await c.send(new AbortMultipartUploadCommand({Bucket:INTERNAL,Key:b.key,UploadId:b.upload_id}));return NextResponse.json({ok:true})}
 if(action==='confirm'){const key=String(b.key||'');if(!key.startsWith(`projects/${projectId}/reference/`))return NextResponse.json({error:'Invalid key'},{status:400});const {data,error}=await a.from('project_files').insert({project_id:projectId,deliverable_id:null,file_name:String(b.file_name||key.split('/').pop()),storage_path:key,r2_key:key,r2_bucket:INTERNAL,storage_provider:'cloudflare_r2',mime_type:String(b.mime_type||'application/octet-stream'),size_bytes:Number(b.size_bytes||0),uploaded_by:user.id,file_role:'reference',creator_visible:true}).select('*').single();if(error)throw error;return NextResponse.json({file:data})}
 return NextResponse.json({error:'Unknown action'},{status:400})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||500})}}
